services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PGVECTOR_VERSION: "0.8.1"
    image: moustachir/postgres:18.1
    container_name: moustachir-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme         # CHANGE THIS in production
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    restart: unless-stopped
    shm_size: "256mb"                     # Recommended for PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local
